### ISSUE TITLE
support k8s 1.30

### ISSUE THREAD

**Issue by YZ775** [cybozu-go/moco#730]
## What

support k8s 1.30

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

```[tasklist]
### Tasks
- [ ] https://github.com/cybozu-go/moco/pull/729
- [ ] https://github.com/cybozu-go/moco/pull/728
- [ ] https://github.com/cybozu-go/moco/pull/727
```
